http:
- matchers:
  - status:
    - 200
    type: status
  - condition: and
    type: word
    words:
    - '"status":'
    - '"success"'
    - '"data":'
    - '"resultType":'
    - '"scalar"'
    - '58596'
  - part: header
    type: word
    words:
    - application/json
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/api/datasources/proxy/1/api/v1/query?query=114*514'
id: prometheus-webapi-via-grafana
info:
  author: Esonhugh-self-maintained
  description: A Prometheus API endpoint via grafana Public Access was discovered.
  name: Prometheus Config API Endpoint Discovery
  reference:
  - https://hackerone.com/reports/764731
  severity: medium
  tags: prometheus,grafana,cloud
