http:
- matchers:
  - condition: and
    dsl:
    - contains_all(body, "window._env_", "CENTRAL_API_ENDPOINT", "DEVTRON_APP_DETAILS_POLLING_INTERVAL")
    - contains(content_type, "application/javascript")
    - status_code == 200
    type: dsl
  method: GET
  path:
  - '{{BaseURL}}/dashboard/env-config.js'
id: devtron-env-config-js
info:
  author: johnk3r
  description: 'Devtron JavaScript environment configuration file was identified at
    /dashboard/env-config.js, exposing internal API endpoints and feature flag settings.

    '
  metadata:
    fofa-query: title="Devtron"
    max-request: 1
    product: devtron
    shodan-query: http.title:"Devtron"
    vendor: devtron-labs
    verified: true
  name: Devtron JavaScript Environment Configuration - Exposure
  reference:
  - https://github.com/devtron-labs/devtron
  severity: low
  tags: config,devtron,exposure,javascript
