http:
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - ListConfigFilesResponse
    - <configfiles>
  - status:
    - 200
    type: status
  matchers-condition: and
  raw:
  - "POST / HTTP/1.1\nHost: {{Hostname}}\nContent-Type: text/xml; charset=UTF-8\n\
    SOAPAction: '\"\"'\n\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<SOAP-ENV:Envelope\
    \ xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <SOAP-ENV:Header>\n\
    \    <sapsess:Session xmlns:sapsess=\"http://www.sap.com/webas/630/soap/features/session/\"\
    >\n      <enableSession>true</enableSession>\n    </sapsess:Session>\n  </SOAP-ENV:Header>\n\
    \  <SOAP-ENV:Body>\n    <ns1:ListConfigFiles xmlns:ns1=\"urn:SAPControl\"/>\n\
    \  </SOAP-ENV:Body>\n</SOAP-ENV:Envelope>\n"
id: sap-listconfigfiles-disclosure
info:
  author: LRVT,l4rm4nd
  description: 'Detected SAP systems where the SAP Start Service (sapstartsrv) SAPControl
    SOAP interface exposes the ListConfigFiles web method without authentication.

    '
  metadata:
    max-request: 1
  name: SAPControl ListConfigFiles - Disclosure
  reference:
  - https://itsiti.com/csmon/
  - https://cloud.ibm.com/docs/sap?topic=sap-monitoring-prereqs
  - https://help.sap.com/docs/SUPPORT_CONTENT/si/3362959700.html
  severity: medium
  tags: misconfig,sap,sapcontrol,soap,config,disclosure
