http:
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - Welcome to the BIG-IP
    - Configuration Utility
  method: GET
  path:
  - '{{BaseURL}}/tmui/login.jsp'
  - '{{BaseURL}}/tmui/tmui/login/welcome.jsp'
- matchers:
  - condition: and
    part: header
    type: word
    words:
    - 'Www-Authenticate: Basic realm'
    - Enterprise Manager
  - part: body
    type: word
    words:
    - check your user-id and password and try again
  method: GET
  path:
  - '{{BaseURL}}/mgmt/tm/sys/management-ip'
id: bigip-config-utility
info:
  author: dwisiswant0
  metadata:
    max-request: 3
  name: BIG-IP Configuration Utility detected
  severity: info
  tags: tech,bigip
