file:
- extensions:
  - all
  matchers:
  - name: Debuggable
    type: word
    words:
    - android:debuggable="true"
  - name: Allow Backup
    type: word
    words:
    - android:allowBackup="true"
  - name: Android exported enabled
    type: word
    words:
    - android:exported="true"
id: Identify Config issue in Android apk file
info:
  author: rahulkadavil
  description: This template can be used to detect basic Configuration issues from
    the apk
  name: Configuration issues in Android apk file
  severity: medium
  tags: Configuration issues
