http:
- matchers:
  - condition: and
    type: word
    words:
    - LibreChat
    - serverDomain
    - registrationEnabled
    - passwordResetEnabled
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/api/config'
id: librechat-config-exposure
info:
  author: icarot
  classification:
    cpe: cpe:2.3:a:librechat:librechat:-:*:*:*:*:*:*:*
  description: 'Detected the `/api/config` endpoint of the LibreChat web application
    was publicly accessible, potentially exposing internal configuration details.

    '
  metadata:
    max-request: 1
    product: librechat
    shodan-query: title:"librechat"
    vendor: librechat
    verified: true
  name: librechat - Config Exposure
  severity: low
  tags: config,exposure,librechat
