http:
- extractors:
  - group: 1
    regex:
    - (?i)Copyright\s+&copy;\s+([0-9,\s]+),\s+Oracle
    type: regex
  host-redirects: true
  matchers:
  - condition: and
    dsl:
    - status_code == 200
    - contains_any(to_lower(body), "login to oracle application server control", "oracle
      enterprise manager")
    type: dsl
  max-redirects: 2
  method: GET
  path:
  - '{{BaseURL}}/em/console/ias/oc4j/home'
  - '{{BaseURL}}'
  stop-at-first-match: true
id: oracle-application-server-panel
info:
  author: righettod
  description: 'Oracle Application Server login panel was detected.

    '
  metadata:
    max-request: 1
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)Oracle Containers
      for J2EE"})
    shodan-query: http.title:"Oracle Containers for J2EE"
    verified: true
  name: Oracle Application Server Panel - Detect
  reference:
  - https://www.oracle.com/middleware/technologies/internet-application-server.html
  severity: info
  tags: panel,oracle,containers,login,detect,discovery
