id: trueconf-bdu-2025-10116
info:
  author: collapsz
  description: A vulnerability in the TrueConf Server allows remote attackers to execute
    arbitrary OS commands via unsanitized input. This issue affects multiple builds
    of TrueConf Server.
  name: TrueConf Server OS Command Injection
  reference:
  - https://bdu.fstec.ru/vul/2025-10116
  severity: critical
  tags: trueconf,bdu,rce
requests:
- extractors:
  - json:
    - .version
    name: version
    type: json
  matchers:
  - dsl:
    - '(regex("^5\\.3\\.", version) && compare_versions(version, "< 5.3.7")) ||

      (regex("^5\\.4\\.", version) && compare_versions(version, "< 5.4.6")) ||

      (regex("^5\\.5\\.0\\.", version)) ||

      (regex("^5\\.5\\.1\\.", version) && compare_versions(version, "< 5.5.1.10180"))

      '
    type: dsl
  method: GET
  path:
  - '{{BaseURL}}/api/v3/server'
