http:
- matchers:
  - part: body
    regex:
    - ^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+
    type: regex
  - status:
    - 200
    type: status
  - negative: true
    part: header
    type: word
    words:
    - text/html
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/dockerfile'
  - '{{BaseURL}}/Dockerfile'
id: dockerfile-disclosure
info:
  author: morgenm
  description: Searches for exposed Dockerfiles.
  name: Dockerfile File Detection
  severity: medium
  tags: exposure,config
