id: dockerfile-hidden-disclosure2
info:
  author: dhiyaneshDk
  name: Dockerfile Hidden Disclosure
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  severity: medium
  tags: exposure,config
requests:
- matchers:
  - part: body
    regex:
    - ^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+
    type: regex
  - status:
    - 200
    type: status
  - negative: true
    part: header
    type: word
    words:
    - text/html
  matchers-condition: and
  raw:
  - 'GET /.Dockerfile HTTP/1.1

    Host: {{Hostname}}

    User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

    Accept-Encoding: gzip, deflate

    Accept: */*

    '
