http:
- extractors:
  - group: 1
    name: version
    part: body
    regex:
    - (?mi)Stable tag:\s*([0-9.]+)
    type: regex
  matchers:
  - status:
    - 200
    type: status
  - part: body
    type: word
    words:
    - wp-configurator-pro
  - dsl:
    - compare_versions(version, '<= 3.7.9')
    type: dsl
  matchers-condition: and
  max-redirects: 3
  method: GET
  path:
  - '{{BaseURL}}/wp-content/plugins/wp-configurator-pro/readme.txt'
  redirects: true
id: wp_configurator_pro-075dce39-f06c-4ab3-a1ec-2669f32a81ab
info:
  author: topscoder
  classification:
    cve-id: null
    cvss-metrics: null
    cvss-score: null
  description: ''
  metadata:
    fofa-query: wp-content/plugins/wp-configurator-pro/
    google-query: inurl:"/wp-content/plugins/wp-configurator-pro/"
    shodan-query: http.html:"wp-content/plugins/wp-configurator-pro/"
  name: 'WP Configurator Pro <= 3.7.9 - Missing Authorization

    '
  reference:
  - https://github.com/topscoder/nuclei-wordfence-cve
  - https://www.wordfence.com/threat-intel/vulnerabilities/id/075dce39-f06c-4ab3-a1ec-2669f32a81ab?source=api-scan
  severity: high
  tags: cve,wordpress,wp-plugin,wp-configurator-pro,high,candidate
