flow: http(1) && http(2)
http:
- matchers:
  - internal: true
    part: body
    type: word
    words:
    - plugins/wordfence
  method: GET
  path:
  - '{{BaseURL}}'
  redirects: true
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - authKey"
    - '{s'
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/wp-content/wflogs/config.php'
  - '{{BaseURL}}/wp-content/wflogs/config-synced.php'
  stop-at-first-match: true
id: wordfence-config-disclosure
info:
  author: ritikchaddha
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  description: 'The Wordfence Security plugin for WordPress stores configuration files
    in the /wp-content/wflogs/ directory. These files may be accessible without authentication
    and can expose sensitive configuration data, firewall rules, attack logs, and
    internal paths.

    '
  metadata:
    fofa-query: body="/plugins/wordfence"
    max-request: 2
    runzero-match: service["http.body"] matches "(?i)/plugins/wordfence"
    verified: true
  name: WordPress Wordfence - Configuration File Disclosure
  reference:
  - https://wordpress.org/support/topic/files-created-in-wflogs-before-plugin-activated/
  - https://forum.ait-pro.com/forums/topic/wordfence-firewall-wp-contentwflogsconfig-php-file-quarantined/
  severity: medium
  tags: wordpress,wp,wp-plugin,wordfence,config,exposure
