http:
- extractors:
  - group: 1
    name: version
    part: body
    regex:
    - (?mi)Stable tag:\s*([0-9.]+)
    type: regex
  matchers:
  - status:
    - 200
    type: status
  - part: body
    type: word
    words:
    - product-import-export-for-woo
  - dsl:
    - compare_versions(version, '<= 2.5.6')
    type: dsl
  matchers-condition: and
  max-redirects: 3
  method: GET
  path:
  - '{{BaseURL}}/wp-content/plugins/product-import-export-for-woo/readme.txt'
  redirects: true
id: product_import_export_for_woo-c506c0fb-d853-45d2-b6d5-9c3b1fa4f1e8
info:
  author: topscoder
  classification:
    cve-id: null
    cvss-metrics: null
    cvss-score: null
  description: ''
  metadata:
    fofa-query: wp-content/plugins/product-import-export-for-woo/
    google-query: inurl:"/wp-content/plugins/product-import-export-for-woo/"
    shodan-query: http.html:"wp-content/plugins/product-import-export-for-woo/"
  name: "Product Import Export for WooCommerce \u2013 Import Export Product CSV Suite\
    \ <= 2.5.6 - Missing Authorization\n"
  reference:
  - https://github.com/topscoder/nuclei-wordfence-cve
  - https://www.wordfence.com/threat-intel/vulnerabilities/id/c506c0fb-d853-45d2-b6d5-9c3b1fa4f1e8?source=api-scan
  severity: high
  tags: cve,wordpress,wp-plugin,product-import-export-for-woo,high,candidate
